# Default values

replicaCount: 1

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

image:
  repository: ghcr.io/ademayowa/events-app
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  name: events-api-service

namespace: events-dev

config:
  ginMode: debug # Development mode uses "debug" for the GIN framework

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 500m

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
